## Basic Configuration
title: "RPGReki's Misadventures"
description: "Creative Writing, Mahjong and more!"
source: site
destination: docs

timezone: Europe/Berlin
future: true

url: 'https://reki.wtf'

excerpt_separator: "<!--more-->"
feed: /feeds/chapters.xml

include:
  - ".dev"

permalink: pretty

### Copyright
copyright:
  license: <a rel="license" href="https://creativecommons.org/licenses/by/4.0/">CC-BY 4.0</a>
  name: RPGReki
  url: /about-me/


### SASS
sass:
  style: compressed
  cache: false

### Plugins
plugins:
  - jekyll-regex-replace
  - jekyll-include-cache
  - jekyll-liquify
  - jekyll-criticmarkup
  - jekyll-wns
  - jekyll-last-modified-at

## SEO
twitter:
  username: RPGReki
  card: summary
facebook:
  app_id: 656032504831426
tumblr:
  url: RPGReki.tumblr.com
bluesky:
  username: "@rpgreki.vtubers.social"
mastodon:
  username: RPGReki@vt.social
google_analytics: UA-143950814-4
patreon:
  title: Become a Patron to read early access chapters
  url: https://www.patreon.com/bePatron?u=27792463
webmaster_verifications:
  - name: seobility
    key: efc87fbbcdcf8f61c070bbcc23dab8b1
  - name: "flattr:id"
    key: ol39pw
  - name: yandex-verification
    key: 6ffa84e7e6fe0f02
  - name: "msvalidate.01"
    key: 6AC9CB5682E608DAAC61DB673BDE81A4
favicon:
  href: /icon.svg
  type: image/svg+xml
alt-icon:
  href: /icon.ico
mask-icon:
  href: /mark-icon.svg
  color: '#9c2c2c'

# Optimizations
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: [p, li, td, rb, rp, rt, dt, dd, tr, td, th]
  blanklines: false
  profile: false
  startings: []
  ignore:
    envs:

preload:
  fonts:
  - /assets/fonts/Cardo-Regular.woff2
  - /assets/fonts/SourceSans3-Regular.woff2
  - /assets/fonts/SourceSans3-Bold.woff2

liquid:
  error_mode: warn

token:
  max: 2147483647
  mod:  899981
  plus: 100000

# Syntax
markdown: kramdown

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"] # Smartquotes off

wns:
  quads: true
  abbreviations: true
  label_unicode: true
#  label_pronounciation:
#    - term: Dewick
#      pronounciation: Duwick

# Comments
comments:
  action: /thanks-for-commenting/

## Defaults
defaults:
  - # /
    scope:
      path: ""
    values:
      lang: "en-AU"
      author: reki
      publisher: reki
      comments: false
      image: /images/-og.jpg
  - # /de
    scope:
      path: "de"
    values:
      lang: "de-DE"
      author: reki
      publisher: reki
      comments: false
      image: /images/-og.jpg
      sitemap: false
  - # /_posts/personal
    scope:
      path: "_posts/personal"
    values:
      category: personal
      layout: 2021/post
      type: post
      lang: "en-AU"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      image: /images/-og.jpg
      permalink: /blog/:year/:month-:day-:title/
      audio_mirror: 
        - https://reki.wtf/blog/audio/
        - https://reki-adventures.s3.eu-central-1.amazonaws.com/
  - # /_posts/amauga
    scope:
      path: "_posts/amauga"
    values:
      category: amauga
      layout: 2021/post
      type: post
      lang: "de-DE"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      image: /amauga/-og.jpg
      permalink: /amauga/blog/:year/:month-:day-:title/
  - # /_posts/crystaldown
    scope:
      path: "_posts/crystaldown"
    values:
      category: crystaldown
      layout: 2021/post
      type: post
      lang: "en-AU"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      image: /crystaldown/-og.jpg
      permalink: /crystaldown/blog/:year/:month-:day-:title/
      intermediate_breadcrumbs:
        -
          title: Archived Projects
          url: /archive/
  - # /amauga/01-weit-weit-weg-von-moderner-zivilization
    scope:
      path: "amauga/01-weit-weit-weg-von-moderner-zivilization"
    values:
      layout: 2021/chapter
      type: chapter
      lang: "de-DE"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      termbase: /amauga
      book:
        number: 1
        series: Amauga
        copyrightYear: 2026
        title: "Weit, weit weg von moderner Zivilisation"
        url: "/amauga/#band01"
        genres:
          - Science Fantasy
          - Fantasy
          - Action & Adventure
          - Slice of Life
      image: /amauga/-og.jpg
  - # /amauga/02-first-steps-of-the-pilgrimage
    scope:
      path: "amauga/02-first-steps-of-the-pilgrimage/"
    values:
      layout: 2021/chapter
      type: chapter
      lang: "en-AU"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      termbase: /amauga
      book:
        number: 2
        series: Amauga
        copyrightYear: 2021
        title: First Steps of the Pilgrimage
        url: "/amauga/#band02"
        genres:
          - Adventure
          - Fantasy
          - Slice of Life
      audio_mirror:
        - "https://amauga.s3.us-east-2.amazonaws.com/"
      image: /amauga/-og.jpg
  - # /private
    scope:
      path: "private"
    values:
      layout: base
      sitemap: false
      image: /images/-og.jpg
      robots: noindex, nofollow
