## Basic Configuration
title: "RPGReki's Misadventures"
description: "Creative Writing, Mahjong and more!"
source: site
destination: docs

timezone: Europe/Berlin
future: true

url: 'https://reki.wtf'

excerpt_separator: "<!--more-->"
feed: /feeds/chapters.xml

include:
  - ".dev"

permalink: pretty

### Copyright
copyright:
  license: <a rel="license" href="https://creativecommons.org/licenses/by/4.0/">CC-BY 4.0</a>
  name: RPGReki
  url: /about-me/


### SASS
sass:
  style: compressed
  cache: false

### Plugins
plugins:
  - jekyll-regex-replace
  - jekyll-include-cache
  - jekyll-liquify
  - jekyll-criticmarkup
  - jekyll-wns
  - jekyll-last-modified-at

## SEO
twitter:
  username: RPGReki
  card: summary
facebook:
  app_id: 656032504831426
tumblr:
  url: RPGReki.tumblr.com
mastodon:
  username: RPGReki@vt.social
google_analytics: UA-143950814-4
patreon:
  title: Become a Patron to read early access chapters
  url: https://www.patreon.com/bePatron?u=27792463
webmaster_verifications:
  - name: seobility
    key: efc87fbbcdcf8f61c070bbcc23dab8b1
  - name: "flattr:id"
    key: ol39pw
  - name: yandex-verification
    key: 6ffa84e7e6fe0f02
  - name: "msvalidate.01"
    key: 6AC9CB5682E608DAAC61DB673BDE81A4
favicon:
  href: /icon.svg
  type: image/svg+xml
alt-icon:
  href: /icon.ico
mask-icon:
  href: /mark-icon.svg
  color: '#9c2c2c'

# Optimizations
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: [p, li, td, rb, rp, rt, dt, dd, tr, td, th]
  blanklines: false
  profile: false
  startings: []
  ignore:
    envs:

preload:
  fonts:
  - /assets/fonts/Cardo-Regular.woff2
  - /assets/fonts/SourceSans3-Regular.woff2
  - /assets/fonts/SourceSans3-Bold.woff2

liquid:
  error_mode: warn

token:
  max: 2147483647
  mod:  899981
  plus: 100000

# Syntax
markdown: kramdown

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"] # Smartquotes off

wns:
  quads: true
  abbreviations: true
  label_unicode: true
#  label_pronounciation:
#    - term: Dewick
#      pronounciation: Duwick

# Comments
comments:
  action: /thanks-for-commenting/

## Defaults
defaults:
  - # /
    scope:
      path: ""
    values:
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: false
      image: /images/-og.jpg
  - # /_posts/personal
    scope:
      path: "_posts/personal"
    values:
      category: personal
      layout: 2021/post
      type: post
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      image: /images/-og.jpg
      permalink: /blog/:year/:month-:day-:title/
      audio_mirror: 
        - https://reki.wtf/blog/audio/
        - https://reki-adventures.s3.eu-central-1.amazonaws.com/
  - # /_posts/amauga
    scope:
      path: "_posts/amauga"
    values:
      category: amauga
      layout: 2021/post
      type: post
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      image: /amauga/-og.jpg
      permalink: /amauga/blog/:year/:month-:day-:title/
  - # /_posts/crystaldown
    scope:
      path: "_posts/crystaldown"
    values:
      category: crystaldown
      layout: 2021/post
      type: post
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      image: /crystaldown/-og.jpg
      permalink: /crystaldown/blog/:year/:month-:day-:title/
      intermediate_breadcrumbs:
        -
          title: Archived Projects
          url: /archive/
  - # /_posts/scions
    scope:
      path: "_posts/scions"
    values:
      category: scions
      layout: 2021/post
      type: post
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      image: /crystaldown/-og.jpg
      permalink: /scions/blog/:year/:month-:day-:title/
      intermediate_breadcrumbs:
        -
          title: Archived Projects
          url: /archive/
  - # /_posts/scions-reboot
    scope:
      path: "_posts/scions-reboot"
    values:
      category: scions-reboot
      layout: 2021/post
      type: post
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      image: /images/-og.jpg
      permalink: /scions-reboot/blog/:year/:month-:day-:title/
  - # /_posts/my-life-as-a-cat
    scope:
      path: "_posts/my-life-as-a-cat"
    values:
      category: my-life-as-a-cat
      layout: 2021/post
      type: post
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      image: /images/-og.jpg
      permalink: /my-life-as-a-cat/blog/:year/:month-:day-:title/
  - # /crystal-down-reboot/01-life-in-avan-forest
    scope:
      path: "crystal-down-reboot/01-life-in-avan-forest"
    values:
      layout: 2021/chapter
      type: chapter
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      termbase: /crystal-down-reboot
      book:
        number: 1
        series: Crystal Down
        copyrightYear: 2023-2020
        title: "Life in Avan Forest"
        url: "/crystal-down-reboot/#volume01-lifeinavanforest"
        genres:
          - Comedy
          - Fantasy
          - Isekai
          - LitRPG
          - Slice of Life
      image: /crystal-down-reboot/-og.jpg
  - # /crystaldown/01-life-in-avan-forest
    scope:
      path: "crystaldown/01-life-in-avan-forest"
    values:
      layout: 2021/chapter
      type: chapter
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      termbase: /crystaldown
      book:
        number: 1
        series: Crystal Down
        copyrightYear: 2019-2020
        title: "Life in Avan Forest"
        url: "/crystaldown/#volume01-lifeinavanforest"
        genres:
          - Comedy
          - Fantasy
          - Isekai
          - LitRPG
          - Slice of Life
      image: /crystaldown/-og.jpg
      intermediate_breadcrumbs:
        -
          title: Archived Projects
          url: /archive/
  - # /crystaldown/02-vampire-aide-and-exodus
    scope:
      path: "crystaldown/02-vampire-aide-and-exodus"
    values:
      layout: 2021/chapter
      type: chapter
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      termbase: /crystaldown
      book:
        number: 2
        series: Crystal Down
        copyrightYear: 2020-2021
        title: "Vampire Aide and Exodus"
        url: "/crystaldown/#volume02-vampireaideandexodus"
        genres:
          - Comedy
          - Fantasy
          - Isekai
          - LitRPG
          - Slice of Life
      image: /crystaldown/-og.jpg
      intermediate_breadcrumbs:
        -
          title: Archived Projects
          url: /archive/
  - # /scions/01-children-of-light-and-darkness
    scope:
      path: "scions/01-children-of-light-and-darkness"
    values:
      layout: 2021/chapter
      type: chapter
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      termbase: /crystaldown
      book:
        number: 1
        series: "Crystal Down: Scions"
        copyrightYear: 2020
        title: "Children of Light and Darkness"
        url: "/scions/#volume-01-children-of-light-and-darkness"
        genres:
          - Adventure
          - Fantasy
          - LitRPG
          - Slice of Life
      image: /crystaldown/-og.jpg
      intermediate_breadcrumbs:
        -
          title: Archived Projects
          url: /archive/
  - # /amauga/01-far-from-any-semblance-of-modern-civilization
    scope:
      path: "amauga/01-far-from-any-semblance-of-modern-civilization/"
    values:
      layout: 2021/chapter
      type: chapter
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      termbase: /amauga
      book:
        number: 1
        series: Amauga
        copyrightYear: 2021
        title: "Far From Any Semblance of Modern Civilization"
        url: "/amauga/#volume01-farfromanysemblance-ofmoderncivilization"
        genres:
          - Adventure
          - Fantasy
          - Slice of Life
      audio_mirror:
        - "https://amauga.s3.us-east-2.amazonaws.com/"
      image: /amauga/-og.jpg
  - # /amauga/02-first-steps-of-the-pilgrimage
    scope:
      path: "amauga/02-first-steps-of-the-pilgrimage/"
    values:
      layout: 2021/chapter
      type: chapter
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      termbase: /amauga
      book:
        number: 2
        series: Amauga
        copyrightYear: 2021
        title: First Steps of the Pilgrimage
        url: "/amauga/#volume02-firststepsofthepilgrimage"
        genres:
          - Adventure
          - Fantasy
          - Slice of Life
      audio_mirror:
        - "https://amauga.s3.us-east-2.amazonaws.com/"
      image: /amauga/-og.jpg
  - # /my-life-as-a-cat/
    scope:
      path: "my-life-as-a-cat/"
    values:
      sitemap: false
      robots: noindex
  - # /my-life-as-a-cat/01
    scope:
      path: "my-life-as-a-cat/01-working-title/"
    values:
      layout: 2021/chapter
      type: chapter
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      termbase: /my-life-as-a-cat
      book:
        number: 1
        series: My Life As A Cat
        copyrightYear: 2022
        title: Reincarnation
        url: "/my-life-as-a-cat/#volume01-reincarnation"
        genres:
          - Fantasy
          - Slice of Life
          - Comedy
          - LitRPG
          - Isekai
      image: /images/-og.jpg
  - # /private
    scope:
      path: "private"
    values:
      layout: base
      sitemap: false
      image: /images/-og.jpg
      robots: noindex, nofollow
