## Basic Configuration
title: "0xReki's Adventures by Night"
description: "Creative Writing, Mahjong and more!"
source: site
destination: docs

url: "https://0xreki.de"
static_url: "https://static.0xreki.de"
shorturl:
  -
    url: "https://amau.ga/"
    prefix: "/a/"
  -
    url: "https://cd-ht.ml/"
    prefix: "/cd/"

excerpt_separator: "<!--more-->"
feed: /feeds/chapters.xml
exclude:
  - "build.sh"
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE.md"
  - "README.md"
  - "**/*.xcf"
  - "**/.*"
  - "**/.map"
  - "_theme"
  - "**/Makefile"
  
include:
  - "_headers"
  - "_redirects"
  - ".private"
  - ".dev"

permalink: pretty
future: true

### Copyright
copyright:
  license: <a rel="license" href="https://creativecommons.org/licenses/by/4.0/">CC-BY 4.0</a>
  name: Thai “0xReki” Chung
  url: https://0xreki.de/about-me/


### SASS
sass:
  style: compressed
  cache: false

### Plugins
plugins:
  - jekyll-last-modified-at
  - jekyll-regex-replace
  - jekyll-include-cache
  - jekyll-liquify
  - jekyll-criticmarkup
  - jekyll-wns

## SEO
twitter:
  username: 0xReki
  card: summary
facebook:
  app_id: 656032504831426
tumblr:
  url: tumblr.0xreki.de
google_analytics: UA-143950814-4
patreon:
  title: Become a Patron to read early access chapters
  url: https://www.patreon.com/RWNS
webmaster_verifications:
  - name: seobility
    key: efc87fbbcdcf8f61c070bbcc23dab8b1
  - name: "flattr:id"
    key: ol39pw
  - name: yandex-verification
    key: 323210d55347b761

# Optimizations
compress_html:
  clippings: []
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: false
  profile: false
  startings: [html, head, body]
  ignore:
    envs: [debug]

preload:
  fonts:
  - /assets/fonts/Cardo-Regular.woff2
  - /assets/fonts/Cardo-Bold.woff2
  - /assets/fonts/Source-Sans-Pro-Regular.woff2
  - /assets/fonts/Source-Sans-Pro-Bold.woff2

liquid:
  error_mode: warn

token:
  max: 2147483647
  mod:  899998
  plus: 100000

# Syntax
markdown: kramdown

wns:
  quads: true
  abbreviations: true
  label_unicode: true

# Comments
comments:
  action: /thanks-for-commenting/

## Defaults
defaults:
  - # /
    scope:
      path: ""
    values:
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: false
      image: /assets/images/site-og.webp
  - # /_posts/personal
    scope:
      path: "_posts/personal"
    values:
      category: personal
      layout: 2020/post
      type: post
      lang: "en-CA"
      author: reki
      publisher: reki
      image: /assets/images/site-og.webp
      comments: true
      commenting: open
      published: true
      image: /assets/images/site-og.webp
      permalink: /:year/:month-:day-:title/
      audio_mirror: 
        - https://reki-adventures.s3.eu-central-1.amazonaws.com/
  - # /_posts/amauga
    scope:
      path: "_posts/amauga"
    values:
      category: amauga
      layout: 2020/post
      type: post
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      image: /amauga/-og.webp
      permalink: /amauga/blog/:year/:month-:day-:title/
  - # /_posts/crystaldown
    scope:
      path: "_posts/crystaldown"
    values:
      category: crystaldown
      layout: 2020/post
      type: post
      lang: "en-CA"
      author: reki
      publisher: reki
      image: /assets/images/site-og.webp
      comments: true
      commenting: open
      published: true
      image: /assets/images/site-og.webp
      permalink: /crystaldown/blog/:year/:month-:day-:title/
      intermediate_breadcrumbs:
        -
          title: Archived Projects
          url: /archive/
  - # /_posts/scions
    scope:
      path: "_posts/scions"
    values:
      category: scions
      layout: 2020/post
      type: post
      lang: "en-CA"
      author: reki
      publisher: reki
      image: /assets/images/site-og.webp
      comments: true
      commenting: open
      published: true
      image: /assets/images/site-og.webp
      permalink: /scions/blog/:year/:month-:day-:title/
      intermediate_breadcrumbs:
        -
          title: Archived Projects
          url: /archive/
  - # /_posts/scions-reboot
    scope:
      path: "_posts/scions-reboot"
    values:
      category: scions-reboot
      layout: 2020/post
      type: post
      lang: "en-CA"
      author: reki
      publisher: reki
      image: /assets/images/site-og.webp
      comments: true
      commenting: open
      published: true
      image: /assets/images/site-og.webp
      permalink: /scions-reboot/blog/:year/:month-:day-:title/
  - # /_posts/reincarnated-as-cat
    scope:
      path: "_posts/reincarnated-as-cat"
    values:
      category: reincarnated-as-cat
      layout: 2020/post
      type: post
      lang: "en-CA"
      author: reki
      publisher: reki
      image: /assets/images/site-og.webp
      comments: true
      commenting: open
      published: true
      image: /assets/images/site-og.webp
      permalink: /amauga/blog/:year/:month-:day-:title/
  - # /crystaldown/01-life-in-avan-forest
    scope:
      path: "crystaldown/01-life-in-avan-forest"
    values:
      layout: 2020/chapter
      type: chapter
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      termbase: /crystaldown
      book:
        number: 1
        series: Crystal Down
        copyrightYear: 2019-2020
        title: "Life in Avan Forest"
        url: "/crystaldown/#volume01-lifeinavanforest"
        genres:
          - Comedy
          - Fantasy
          - Isekai
          - LitRPG
          - Slice of Life
      image: /assets/images/site-og.webp
      intermediate_breadcrumbs:
        -
          title: Archived Projects
          url: /archive/
  - # /crystaldown/02-vampire-aide-and-exodus
    scope:
      path: "crystaldown/02-vampire-aide-and-exodus"
    values:
      layout: 2020/chapter
      type: chapter
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      termbase: /crystaldown
      book:
        number: 2
        series: Crystal Down
        copyrightYear: 2020-2021
        title: "Vampire Aide and Exodus"
        url: "/crystaldown/#volume02-vampireaideandexodus"
        genres:
          - Comedy
          - Fantasy
          - Isekai
          - LitRPG
          - Slice of Life
      image: /assets/images/site-og.webp
      intermediate_breadcrumbs:
        -
          title: Archived Projects
          url: /archive/
  - # /doman
    scope:
      path: "doman"
    values:
      lang: "en-CA"
      author: reki
      publisher: reki
      intermediate_breadcrumbs:
        -
          title: Doman Mahjong Tournaments
          url: /doman/
  - # /scions/01-children-of-light-and-darkness
    scope:
      path: "scions/01-children-of-light-and-darkness"
    values:
      layout: 2020/chapter
      type: chapter
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      termbase: /crystaldown
      book:
        number: 1
        series: "Crystal Down: Scions"
        copyrightYear: 2020
        title: "Children of Light and Darkness"
        url: "/scions/#volume-01-children-of-light-and-darkness"
        genres:
          - Adventure
          - Fantasy
          - LitRPG
          - Slice of Life
      image: /assets/images/site-og.webp
      intermediate_breadcrumbs:
        -
          title: Archived Projects
          url: /archive/
  - # /amauga/01-far-from-any-semblance-of-modern-civilization
    scope:
      path: "amauga/01-far-from-any-semblance-of-modern-civilization/"
    values:
      layout: 2020/chapter
      type: chapter
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      termbase: /amauga
      book:
        number: 1
        series: Amauga
        copyrightYear: 2021
        title: "Far From Any Semblance of Modern Civilization"
        url: "/amauga/#volume01-farfromanysemblance-ofmoderncivilization"
        genres:
          - Adventure
          - Fantasy
          - Slice of Life
        audio_mirror: 
          - "https://amauga.s3.us-east-2.amazonaws.com/"
      image: /amauga/-og.webp
  - # /reincarnated-as-cat/01
    scope:
      path: "reincarnated-as-cat/01/"
    values:
      layout: 2020/chapter
      type: chapter
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: true
      termbase: /reincarnated-as-cat/
      book:
        number: 1
        series: That Time I Got Reincarnated as a Cat
        copyrightYear: 2022
        title: That Time I Got Reincarnated as a Cat
        url: "/reincarnated-as-cat/#volume01"
        genres:
          - Adventure
          - Fantasy
          - Slice of Life
      image: /assets/images/site-og.webp
  - # /private
    scope:
      path: "private"
    values:
      layout: base
      sitemap: false
      image: /assets/images/site-og.webp
      robots: noindex, nofollow
  - # /scions-reboot/01-children-of-light-and-darkness
    scope:
      path: "scions-reboot/01-children-of-light-and-darkness"
    values:
      layout: 2020/chapter
      type: chapter
      lang: "en-CA"
      author: reki
      publisher: reki
      comments: true
      commenting: open
      published: pre-sponsor
      termbase: /none/
      book:
        number: 1
        series: "Scions Reboot"
        copyrightYear: 2022
        title: "Children of Light and Darkness"
        url: "/scions-reboot/#volume-01-children-of-light-and-darkness"
        genres:
          - Adventure
          - Fantasy
          - LitRPG
          - Slice of Life
      image: /assets/images/site-og.webp
