#!/bin/bash

STORIES=(crystaldown scions amauga reincarnated-as-cat)

trap 'rm wait.fifo' EXIT
mkfifo wait.fifo

# Prepare Posts
(
  # rm -rf personal-blog
  # git clone "https://oauth2:${GITLAB_TOKEN}@gitlab.com/0xReki/personal-blog.git" --quiet

  rm -rf site/_posts/personal
  mkdir -p site/_posts/personal
  rsync -r personal-blog/_posts/* site/_posts/personal/

  rm -rf site/blog
  rsync -r personal-blog/blog site/
  : > wait.fifo
  echo personal-blog imported.
) &

rm -rf site/_data/{amauga,cd}

for i in "${STORIES[@]}"; do
  (
    # rm -rf "${i}"
    # git clone "https://oauth2:${GITLAB_TOKEN}@gitlab.com/0xReki.WN/${i}.git" --quiet
 
    rm -rf "site/_posts/${i}"
    mkdir -p "site/_posts/${i}"
    rsync -r "${i}/_posts/"* "site/_posts/${i}/"
  
    rm -rf "site/${i}"
    mkdir -p "site/${i}"
    rsync -r "${i}/pages/"* "site/${i}/"

    if [ "${i}" = "amauga" ]; then
      rsync -r amauga/_data site/_data/amauga
    fi

    if [ "${i}" = "crystaldown" ]; then
      rsync -r crystaldown/_data site/_data/cd
    fi
    
    : > wait.fifo
    echo ${i} imported.
  ) & 
done

( 
  node_modules/.bin/gulp get-comments --quiet
  : > wait.fifo
  echo comments imported.
) &

for i in "${STORIES[@]}"; do 
  read < wait.fifo
done
read < wait.fifo
read < wait.fifo

rm -rf site/tags
bundle exec jekyll b
bash docs/.dev/createTags.sh
rsync {docs/.dev/js/,theme/assets/2021/scripts/}early.min.js
rsync {docs/.dev/js/,theme/assets/2021/scripts/}late.min.js
