#!/bin/bash

STORIES=(crystaldown scions amauga reincarnated-as-cat)

# Prepare Posts
(
  cd personal-blog || exit
  git pull --quiet
) || (
  rm -rf personal-blog
  git clone "https://oauth2:${GITLAB_TOKEN}@gitlab.com/0xReki/personal-blog.git"
)

rm -rf site/_posts/personal
mkdir -p site/_posts/personal
cp -r personal-blog/_posts/* site/_posts/personal/

rm -rf site/blog
cp -r personal-blog/blog site/

for i in "${STORIES[@]}"; do
  (
    cd "${i}" || exit
    git pull --quiet
  ) || (
    rm -rf "${i}"
    git clone "https://oauth2:${GITLAB_TOKEN}@gitlab.com/0xReki.WN/${i}.git"
  )  
 
  rm -rf "site/_posts/${i}"
  mkdir -p "site/_posts/${i}"
  cp -r "${i}/_posts/"* "site/_posts/${i}/"
  
  rm -rf "site/${i}"
  mkdir -p "site/${i}"
  cp -r "${i}/pages/"* "site/${i}/"
done

bundle exec jekyll b

rm -rf site/tags
bash docs/.dev/createTags.sh

cp {docs/.dev/js/,theme/assets/2021/scripts/}early.min.js
cp {docs/.dev/js/,theme/assets/2021/scripts/}late.min.js

rm -rf site/_data/{amauga,cd}

cp -r amauga/_data site/_data/amauga
cp -r crystaldown/_data site/_data/cd

node_modules/.bin/gulp get-comments
