#!/bin/bash

npm i

# Prepare Theme

if [ -d theme/.git ]; then
  (
    cd theme || exit
    git pull
  )
else
  rm -rf theme
  git clone "https://oauth2:${GITLAB_TOKEN}@gitlab.com/0xReki/crystaldown-theme.git" theme
fi

rm -rf site/_includes site/_layouts site/_sass site/assets
cp -r theme/_includes theme/_layouts theme/_sass theme/assets site
