#!/bin/bash

npm i
echo node_modules installed.

# Prepare Theme

rm -rf theme
git clone "https://oauth2:${GITLAB_TOKEN}@gitlab.com/0xReki/crystaldown-theme.git" theme  --depth 1 --quiet

rm -rf site/_includes site/_layouts site/_sass site/assets
cp -r theme/_includes theme/_layouts theme/_sass theme/assets site

echo theme imported.

