## Rules

Most of these are the result of playing in Final Fantasy XIV Online.

- Red Fives
- Players **start on 25,000 points** and **return 25,000** at the end the hanchan
- Points are divided by 1,000 at the end of the game (e.g. +3,400 becomes +3.4)
- Placement bonuses are +15 / +5 / -5 / -15
  - In case multiple people end up on the same rank, the affected placement bonuses
    are added up and evenly distributed
- The hanchan **ends** if a player falls **below zero points** (tobi)
- South 4 Round also ends when dealership doesn't pass (agariyame)
- Open tanyao is allowed (kuitan ari)
- 13 han and above is a Kazoe Yakuman
  - multiple Yakuman are possible
  - single Yakuman for Four Closed Triplets On Pair Wait, Big Four Winds etc. [^special-yaku]
  - Robbing a Quad (chankan) on closed Kan for Thirteens Orphans (Kokushi musou) is not allowed [^advanced-doman-rules]
- Double ron allowed, no headbump
- Abortive draws for
  - 9 unique terminals/honours in starting hand (kyuushuu kyuuhai) [^advanced-doman-rules]
  - same wind tile as the first 4 discards (suufon renda) [^advanced-doman-rules]
  - 4 kans (suukaikan) and [^advanced-doman-rules]
  - triple Ron (sanchahou) [^advanced-doman-rules]
- No abortive draw for 4 riichi (suucha riichi)
- Nagashi Mangan possible [^special-yaku]

If a Players is late by more than ten minutes they are replaced by a substitute
player for the hanchan.

### On Missed Games and Substituted Players

Substitute players are scored normally and then not included in the ranking. The
player missing the hanchan doesn't get any point and will have a 30 points
penalty.

## Final Fantasy XIV Online

All games are being played in [Final Fantasy XIV Online](https://www.finalfantasyxiv.com/).
To play, a trial account is sufficient. You only need to
[unlock the Gold Saucer](https://ffxiv.consolegameswiki.com/wiki/It_Could_Happen_to_You).
Note, if you're not new to Mahjong, it's recommended to change the display from actual dora to dora indicator.

{% include_relative previous-tournaments.inc %}

## References

[^advanced-doman-rules]: [Doman Mahjong — Advanced Rules](https://na.finalfantasyxiv.com/lodestone/playguide/contentsguide/goldsaucer/doman-mahjong/special_rule/)
[^special-yaku]: [Doman Mahjong — Special Yaku](https://na.finalfantasyxiv.com/lodestone/playguide/contentsguide/goldsaucer/doman-mahjong/yaku_list/#anchor_005)

