## Rules

Most of these are the result of playing in Final Fantasy XIV Online.

- 3 red fives (aka ari)
- players **start on 25,000 points**
- no return, no placement bonus
- hanchan **ends** if a player falls **below zero points** (tobi)
- South 4 Round also ends when dealership doesn't pass (agariyame)
- open tanyao is allowed (kuitan ari)
- 13 han and above is a kazoe yakuman
- cumulative single yakuman
- double ron allowed, no head bump
- abortive draws for
  - 9 unique terminals/honours in starting hand (kyuushuu kyuuhai) [^advanced-doman-rules]
  - same wind tile as the first 4 discards (suufonsu renda) [^advanced-doman-rules]
  - 4 kan not from the same person (suukaikan) and [^advanced-doman-rules]
  - triple ron (sancha hou) [^advanced-doman-rules]
- no abortive draw for 4 riichi (suucha riichi)
- mangan at draw (nagashi mangan) possible [^special-yaku]

If a player is late by more than ten minutes they are replaced by a substitute
player for the hanchan.

### On Missed Games and Substituted Players

Substitute players are scored normally and then not included in the ranking. The
player missing the hanchan doesn't get any point and will have a 30 points
penalty.

## Final Fantasy XIV Online

All games are being played in [Final Fantasy XIV Online](https://www.finalfantasyxiv.com/).
To play, a trial account is sufficient. You only need to
[unlock the Gold Saucer](https://ffxiv.consolegameswiki.com/wiki/It_Could_Happen_to_You).
Note, if you're not new to Mahjong, it's recommended to change the display from actual dora to dora indicator.

{% include_relative previous-tournaments.inc %}

## References

[^advanced-doman-rules]: [Doman Mahjong — Advanced Rules](https://na.finalfantasyxiv.com/lodestone/playguide/contentsguide/goldsaucer/doman-mahjong/special_rule/)
[^special-yaku]: [Doman Mahjong — Special Yaku](https://na.finalfantasyxiv.com/lodestone/playguide/contentsguide/goldsaucer/doman-mahjong/yaku_list/#anchor_005)

